# Generated by Django 4.1.4 on 2024-01-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_expires_at',
            field=models.DateTimeField(verbose_name='Token Expires at'),
        ),
    ]
